server:
  port: 8080 # 应用服务 WEB 访问端口
spring:
  application:
    name: book
  resources:
      static-locations: classpath:/static/
  mvc:
      static-path-pattern: /static/**

  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.163.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: Yx_990509@163.com
    #授权码
    password: HVPUSAVYMIRMCODZ
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource # 数据源名称
    url: jdbc:mysql://localhost:3306/bookmanage?serverTimezone=Asia/Shanghai # 数据库连接地址
    username: root # 数据库用户名&密码：
    password: 123456

  thymeleaf:
    cache: false # 开启模板缓存（默认值： true ）
    check-template: false # 检查模板是否存在，然后再呈现
    check-template-location: true # 检查模板位置是否正确（默认值 :true ）
    content-type: text/html #Content-Type 的值（默认值： text/html ）
    enabled: true # 开启 MVC Thymeleaf 视图解析（默认值： true ）
    encoding: UTF-8 # 模板编码
    excluded-view-names: # 要被排除在解析之外的视图名称列表，⽤逗号分隔
    mode: HTML5 # 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML5)
    prefix=classpath: /templates/ # 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
    suffix=: .html # 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）

mybatis-plus:
  mapper-locations:
    classpath: mapper/*.xml
  type-aliases-package: com.yanxu.book.entity

pagehelper:
  #分页插件
  helper-dialect: mysql
  params:
    count: countSql
  reasonable: true
  support-methods-arguments: true

















